import profile from "../assets/images/profile.png";
import thumbnail from "../assets/images/thumbnail.png";
import cards from "../assets/images/cards.png";
import path from "../assets/images/path.png";
import logo from "../assets/images/logo.png";
import logoSmall from "../assets/images/logo-small.png";
import empty from "../assets/images/empty.png";
import successfulTraining from "../assets/images/successfulTraining.jpg";
import trainingMarkers from "../assets/images/trainingMarkers.jpg";
import trainingMistakes from "../assets/images/trainingMistakes.jpg";
import motivateDog from "../assets/images/motivateDog.png";
import health1 from "../assets/images/health1.jpg";
import health2 from "../assets/images/health2.jpg";
import health3 from "../assets/images/health3.jpg";
import health4 from "../assets/images/health4.jpg";
import health5 from "../assets/images/health5.png";
import vc1 from "../assets/images/vc1.jpg";
import vc2 from "../assets/images/vc2.jpg";
import vc3 from "../assets/images/vc3.jpg";

export default { profile, thumbnail, cards, path, logo, logoSmall, empty,successfulTraining,trainingMistakes,trainingMarkers,motivateDog,health1,health2,health3,health4,health5,vc1,vc2,vc3 };
